### ISSUE TITLE
What is the purpose of the ===?

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/angular-directive-controllers-readme#3]
There is a commented out line in a couple of the code snippets that says:
`// $scope.handle === 'billgates';`

It's not clear to me what this line is trying to say and this commented isn't referenced in the ReadMe.

**Comment by aturkewi** [comment]
@ipc103 @PeterBell

**Comment by ipc103** [comment]
When we call the directive in in the view with the `handle="billgates"` property, it assigns the `handle` property of our `$scope` object to be `"bill gates"`. I''ll add a line to the readme explaining this
